---
 - hosts: localhost
  #root access to user
   become: true
   tasks:
   - name: login to dockerhub
     command: docker login -u  -p 
   - name: Create docker image for frontend
     command: docker build -t frontend-image -f ~/devops-test/frontend/Dockerfile frontend/
     args:
       chdir: /opt/docker
   - name: Add tag to image
     command: docker tag frontend-image mowadola/frontend-image
   - name: Push image to docker hub
     command: docker push mowadola/frontend-image
   - name: Remove docker image from Ansible node
     command: docker rmi frontend-image mowadola/frontend-image
     ignore_errors: yes
   - name: Create docker image for backend
     command: docker build -t backend-image -f ~/devops-test/backend/Dockerfile backend/
     args:
       chdir: /opt/docker
   - name: Add tag to image
     command: docker tag backendend-image mowadola/backend-image
   - name: Push image to docker hub
     command: docker push mowadola/backend-image
   - name: Remove docker image from Ansible node
     command: docker rmi backend-image mowadola/backend-image
     ignore_errors: yes