---
 - hosts: "PACADPEU1-asg,docker_prod,docker_stage"
   become: true
   tasks:
   - name: install newrelic agent
     command: docker run \
                     -d \
                     --name newrelic-infra \
                     --network=host \
                     --cap-add=SYS_PTRACE \
                     --privileged \
                     --pid=host \
                     -v "/:/host:ro" \
                     -v "/var/run/docker.sock:/var/run/docker.sock" \
                     -e NRIA_LICENSE_KEY=eu01xxbc4708e1fdb63633cc49bb88b3ce5cNRAL \
                     newrelic/infrastructure:lates